# Autogenerated by generate-config in jpm/make-config.janet
(def config @{:ar "ar"
  :auto-shebang true
  :binpath "/home/kgzm/.local/share/mise/installs/github-janet-lang-janet/1.41.2/bin"
  :c++ "c++"
  :c++-link "c++"
  :cc "cc"
  :cc-link "cc"
  :cflags @["-std=c99"]
  :cflags-verbose @[]
  :cppflags @["-std=c++11"]
  :curlpath "curl"
  :dynamic-cflags @["-fPIC"]
  :dynamic-lflags @["-shared" "-lpthread"]
  :gitpath "git"
  :headerpath "/home/kgzm/.local/share/mise/installs/github-janet-lang-janet/1.41.2/include/janet"
  :is-msvc false
  :janet "janet"
  :janet-cflags @[]
  :janet-lflags @["-lm" "-ldl" "-lrt" "-pthread" "-rdynamic"]
  :ldflags @[]
  :lflags @[]
  :libpath "/home/kgzm/.local/share/mise/installs/github-janet-lang-janet/1.41.2/lib"
  :manpath "/home/kgzm/.local/share/mise/installs/github-janet-lang-janet/1.41.2/share/man/man1"
  :modext ".so"
  :nocolor false
  :pkglist "https://github.com/janet-lang/pkgs.git"
  :silent false
  :statext ".a"
  :tarpath "tar"
  :test false
  :use-batch-shell false
  :verbose false})