(defn run
  `Prints kak initialization script to stdout.

  Called by kak on server startup via:
    evaluate-commands %sh{ ok init }

  Responsibilities:
  - Start the kak-tree-sitter daemon (needs $kak_session)
  - Emit kak script that registers all bindings, hooks, and settings

  Everything emitted here is the single source of truth for editor
  behaviour. The kakrc and kak runtime stay vanilla.`
  []

  # Start kak-tree-sitter daemon.
  # $kak_session is available because we're called from within a kak %sh{} block.
  (when-let [session (os/getenv "kak_session")]
    (os/execute ["kak-tree-sitter" "--kakoune"
                 "--init" session
                 "--server" "--daemonize"
                 "--with-highlighting"
                 "--with-text-objects"] :p))

  (print
    ``
# ── overk — generated by: ok init ────────────────────────────────────────────

# ── clipboard ─────────────────────────────────────────────────────────────────
# Mirror every yank-producing key to the system clipboard via OSC 52.
# OSC 52 is forwarded by zellij, kitty, wezterm, and works over SSH —
# no xclip or wl-clipboard required on the host.
#
# NormalKey fires before the key acts, so %val{selection} is exactly
# what y/d/c is about to put in the register.
hook global NormalKey [ydc] %{
    nop %sh{
        # $kak_quoted_selections is shell-quoted by kak — safe for selections
        # containing spaces, newlines, or other special characters.
        # Join all selections with newlines, matching what kak puts in the register.
        eval set -- "$kak_quoted_selections"
        joined=""
        sep=""
        while [ $# -gt 0 ]; do
            joined="${joined}${sep}${1}"
            sep="
"
            shift
        done
        encoded=$(printf '%s' "$joined" | base64 | tr -d '\n')
        printf '\033]52;c;%s\007' "$encoded" > /dev/tty
    }
}
``))
