(import ./clipboard)

(defn run
  `Prints kak initialization script to stdout.
  Called by kak on server startup via:
    evaluate-commands %sh{ ok --api init }

  Starts daemons, then collects registration scripts from all modules.
  This is the only place that knows about the full module list.`
  []

  # Start kak-tree-sitter daemon.
  # $kak_session is available because we're called from within a kak %sh{} block.
  (def log "/tmp/ok-init.log")
  (defn log! [msg] (os/execute ["sh" "-c" (string "printf '%s\\n' " (string/format "%q" msg) " >> " log)] :p))
  (log! (string "=== ok --api init === pid=" (os/getpid)))
  (let [session (os/getenv "kak_session")]
    (log! (string "kak_session=" (or session "(not set)")))
    (log! (string "PATH=" (or (os/getenv "PATH") "(not set)")))
    (if session
      (do
        (log! "starting kak-tree-sitter...")
        (def exit (os/execute ["sh" "-c"
                    (string "kak-tree-sitter --kakoune"
                            " --init " session
                            " --server --daemonize"
                            " --with-highlighting"
                            " --with-text-objects"
                            " 2>>" log)]
                   :p))
        (log! (string "kak-tree-sitter exit=" exit)))
      (log! "WARNING: kak_session not set, skipping kak-tree-sitter")))

  (print (string
    "# ── overk — generated by: ok --api init ─────────────────────────────────────\n"
    "\n"
    "colorscheme default\n"
    "\n"
    # Status line: {keyword} makes "ok" use the theme's keyword face
    "set-option global modelinefmt '{keyword}ok{Default} ── %val{bufname} {{context_info}} {{mode_info}} - %val{client}@{type}%val{session}{Default}'\n"
    "\n"
    (clipboard/register))))
