(defn run
  `Prints kak initialization script to stdout.

  Called by kak on server startup via:
    evaluate-commands %sh{ ok init }

  Responsibilities:
  - Start the kak-tree-sitter daemon (needs $kak_session)
  - Emit kak script that registers all bindings, hooks, and settings

  Everything emitted here is the single source of truth for editor
  behaviour. The kakrc and kak runtime stay vanilla.`
  []

  # Start kak-tree-sitter daemon.
  # $kak_session is available because we're called from within a kak %sh{} block.
  (when-let [session (os/getenv "kak_session")]
    (os/execute ["kak-tree-sitter" "--kakoune"
                 "--init" session
                 "--server" "--daemonize"
                 "--with-highlighting"
                 "--with-text-objects"] :p))

  # Emit kak script. Everything below is evaluated by kak.
  (print
    ```
# ── overk — generated by: ok init ────────────────────────────────────────────

# TODO: settings, bindings, hooks
```)
  )
